name: Frontend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Only run if changes are made in the frontend directory
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Change working directory to frontend
        run: cd frontend

      - name: Print current working directory
        run: pwd

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
